services:
  backend:
    build:
      context: ../server
      dockerfile: Dockerfile.dev
    container_name: kingsgambit_backend
    command: sh -c "python3 manage.py migrate && daphne kingsgambit_backend.asgi:application -b 0.0.0.0 -p 8000"
    volumes:
      - ../server:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY} 
      - DJANGO_SETTINGS_MODULE=kingsgambit_backend.settings

  peerserver:
    build:
      context: ../peerserver
    container_name: kingsgambit_peerserver
    ports:
      - "9000:9000"